# Generated by Django 4.1.3 on 2022-12-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=30)),
                ('quote', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeslot', models.IntegerField(choices=[(0, '08:00 – 08:30'), (1, '08:30 – 09:00'), (2, '09:00 – 09:30'), (3, '09:30 – 10:00'), (4, '10:00 - 10:30'), (5, '10:30 - 11:00'), (6, '11:00 - 11:30'), (7, '11:30 - 12:00'), (8, '12:00 – 12:30'), (9, '12:30 – 13:00'), (10, '13:00 – 13:30'), (11, '13:30 – 14:00'), (12, '14:00 – 14:30'), (13, '14:30 – 15:00'), (14, '15:00 – 15:30'), (15, '15:30 – 16:00')])),
                ('note', models.CharField(default='', max_length=300)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'timeslot')},
            },
        ),
    ]
