# Generated by Django 4.1.3 on 2022-12-06 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'doctor')},
        ),
    ]
