# Generated by Django 4.1.3 on 2022-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_alter_profile_unique_together_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promise',
            field=models.BooleanField(default=False),
        ),
    ]
