# Generated by Django 4.1.3 on 2022-12-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0006_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appointments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctors.appointment'),
        ),
    ]
