# Generated by Django 4.1.3 on 2022-12-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0007_profile_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='appointments',
        ),
    ]
