# Generated by Django 4.1.3 on 2022-12-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0009_profile_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_doctor',
        ),
    ]
